language: ruby
script: bundle exec rake
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
  - bundle --version
rvm:
  - "2.0.0"
matrix:
  allow_failures:
  - rvm: rbx-20mode
